2018-09-24 23:16:41,870 ERROR: Exception on /youth_registrations [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 222, in event_registration
    len = len(upcoming)
UnboundLocalError: local variable 'len' referenced before assignment
2018-09-24 23:17:14,462 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:23:13,083 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:25:13,252 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:29:51,085 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:30:30,911 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:30:37,490 ERROR: Exception on /leagues [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 291, in leagues
    return render_template('leagues.html', title='Leagues', upcoming=upcoming, passed=passed)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/jiahuiwu/Desktop/XCEL/app/templates/leagues.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/jiahuiwu/Desktop/XCEL/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/Users/jiahuiwu/Desktop/XCEL/app/templates/base.html", line 42, in block "navbar"
    <li><a href="{{ url_for(league_registration) }}">{{ 'Registration' }}</a></li>
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/helpers.py", line 305, in url_for
    if endpoint[:1] == '.':
jinja2.exceptions.UndefinedError: 'league_registration' is undefined
2018-09-24 23:32:03,558 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:32:08,792 ERROR: Exception on / [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 28, in index
    leagues=leagues, events=events, activities=activities)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/jiahuiwu/Desktop/XCEL/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/jiahuiwu/Desktop/XCEL/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/Users/jiahuiwu/Desktop/XCEL/app/templates/base.html", line 42, in block "navbar"
    <li><a href="{{ url_for(league_registration) }}">{{ 'Registration' }}</a></li>
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/helpers.py", line 305, in url_for
    if endpoint[:1] == '.':
jinja2.exceptions.UndefinedError: 'league_registration' is undefined
2018-09-24 23:32:23,072 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:32:28,319 ERROR: Exception on /league_registrations [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 295, in league_registration
    upcoming = League().get_upcoming_events()
AttributeError: 'League' object has no attribute 'get_upcoming_events'
2018-09-24 23:32:45,528 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 23:33:15,655 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-25 09:54:33,076 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
