2018-09-24 16:37:06,907 ERROR: Exception on /register_league/2 [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 307, in register_league
    def register_league(league):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'get_teams'
2018-09-24 16:41:45,300 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 16:42:06,239 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 16:42:27,922 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 16:42:44,790 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 16:43:23,288 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 16:45:44,199 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 16:46:49,010 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:08:58,324 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:09:23,832 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:09:31,482 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:09:35,731 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:10:58,618 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:11:49,106 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:12:21,202 ERROR: Exception on /contact [POST] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 347, in contact
    contact = Contact()
NameError: name 'Contact' is not defined
2018-09-24 20:12:41,501 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:13:16,373 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:13:20,228 ERROR: Exception on /contact [POST] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 362, in contact
    send_contact_us_email(contact)
NameError: name 'send_contact_us_email' is not defined
2018-09-24 20:14:07,314 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:15:21,217 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:15:27,364 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:15:32,766 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:15:36,446 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:20:16,133 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 20:20:40,831 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 21:59:16,720 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 21:59:38,668 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 21:59:57,941 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:00:47,966 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:01:32,361 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:02:31,346 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:09:17,607 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:12:38,919 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:13:40,220 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:16:41,340 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:16:49,067 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:19:35,677 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:21:03,718 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:23:22,492 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:25:55,342 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:26:36,723 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:27:06,318 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:28:02,312 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:35:38,998 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:36:41,943 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:50:13,030 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:50:41,614 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-09-24 22:53:03,885 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
