2018-07-13 09:41:32,785 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL0.1/app/__init__.py:48]
2018-07-13 09:53:05,144 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 09:53:17,425 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 09:54:25,915 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 09:54:48,123 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 10:00:22,050 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 10:00:32,931 ERROR: Exception on /admin/event/edit/ [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/model/base.py", line 2076, in edit_view
    return_url=return_url)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/model/edit.html", line 3, in top-level template code
    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 35, in top-level template code
    {% block page_body %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 64, in block "page_body"
    {% block body %}{% endblock %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/model/edit.html", line 32, in block "body"
    {% block edit_form %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/model/edit.html", line 33, in block "edit_form"
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 212, in template
    {% call form_tag(action=action) %}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 191, in template
    {{ caller() }}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 213, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 183, in template
    {{ render_field(form, f, kwargs) }}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/lib.html", line 137, in template
    {{ field(**kwargs)|safe }}
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/form/widgets.py", line 28, in __call__
    return super(Select2Widget, self).__call__(field, **kwargs)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/wtforms/widgets/core.py", line 287, in __call__
    for val, label, selected in field.iter_choices():
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_admin/contrib/sqla/fields.py", line 169, in iter_choices
    yield (pk, self.get_label(obj), obj in self.data)
TypeError: argument of type 'AppenderBaseQuery' is not iterable
2018-07-13 10:02:33,033 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 10:02:38,731 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 10:02:41,359 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 10:06:42,714 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 10:09:07,212 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/XCEL/app/__init__.py:48]
2018-07-13 10:09:23,194 ERROR: Exception on /events/example_1.pdf [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 189, in event
    event = Event.query.filter_by(id=int(event)).first()
ValueError: invalid literal for int() with base 10: 'example_1.pdf'
2018-07-13 10:09:23,198 ERROR: Exception on /events/example_2.pdf [GET] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/XCEL/app/routes.py", line 189, in event
    event = Event.query.filter_by(id=int(event)).first()
ValueError: invalid literal for int() with base 10: 'example_2.pdf'
